[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq_requests"
description = "Requests integration for Ordeq"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
requires-python = ">=3.10"
dependencies = [
    "ordeq>=1.2.0",
    "requests",
]

[tool.ordeq]
group = "ios"

[tool.ordeq-dev]
logo_url = "https://upload.wikimedia.org/wikipedia/commons/a/aa/Requests_Python_Logo.png"

[dependency-groups]
types = ["types-requests"]
test = [
    "fastapi",
    "pydantic",
    "uvicorn",
    "ordeq-files",
    "ordeq-common"
]

[tool.setuptools_scm]
root = "../../"
version_file = "src/ordeq_requests/_version.py"
tag_regex = "^ordeq-requests/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match ordeq-requests/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]
addopts = "--doctest-modules"

[tool.coverage.run]
source = ["src"]
omit = [
    "src/ordeq_requests/_version.py"
]
