[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq_viz"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
requires-python = ">=3.10"
dependencies = [
    "ordeq>=1.0.0",
]

[dependency-groups]
test = [
    "ordeq-common",
    "ordeq-faiss",
    "ordeq-files",
    "ordeq-pandas",
    "ordeq-pymupdf",
    "ordeq-sentence-transformers",
    "ordeq-test-utils",
]

[tool.setuptools_scm]
root = "../../"
version_file = "src/ordeq_viz/_version.py"
tag_regex = "^ordeq-viz/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match ordeq-viz/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.ruff]
extend = "../../pyproject.toml"

[tool.ruff.lint.extend-per-file-ignores]
# Ignore unresolved imports and docstring missing in tests
"tests/*" = ["PLC0415", "D103"]

[tool.coverage.run]
omit = [
    "src/ordeq_viz/_version.py"
]
