[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq_yaml"
description = "YAML integration for Ordeq"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
requires-python = ">=3.10"
dependencies = [
    "ordeq>=1.0.0",
    "pyyaml",
]

[tool.ordeq]
group = "ios"

[dependency-groups]
types = ["types-PyYAML"]
test = [
    "cloudpathlib[s3]>=0.20.0",
    "minio==7.2.15",
    "testcontainers==4.8.1",
]

[tool.setuptools_scm]
root = "../../"
version_file = "src/ordeq_yaml/_version.py"
tag_regex = "^ordeq-yaml/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match ordeq-yaml/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]
addopts = "--doctest-modules"

[tool.coverage.run]
omit = [
    "src/ordeq_yaml/_version.py"
]
