[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq_viz_cli"
description = "Command line interface for Ordeq visualization"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
requires-python = ">=3.10"
dependencies = ["ordeq-viz>=0.4.0"]

[tool.ordeq-dev]
group = "CLI"

[dependency-groups]
test = []

[project.scripts]
ordeq-viz = "ordeq_viz_cli:main"

[tool.setuptools_scm]
root = "../../"
version_file = "src/ordeq_viz_cli/_version.py"
tag_regex = "^ordeq-viz-cli/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match ordeq-viz-cli/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.coverage.run]
omit = [
    "src/ordeq_viz_cli/_version.py"
]
