[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq-manifest"
description = "Manifests for Ordeq projects"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" }
]
requires-python = ">=3.10"
dependencies = [
    "ordeq",
    "pydantic"
]

[tool.ordeq]
group = "framework"

[dependency-groups]
test = [
    "ordeq-common",
    "ordeq-test-utils",
]

[tool.setuptools_scm]
root = "../../"
version_file = "src/ordeq_manifest/_version.py"
tag_regex = "^ordeq-manifest/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match ordeq-manifest/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.coverage.run]
omit = [
    "src/ordeq_manifest/_version.py"
]
