[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq_spark"
description = "Apache Spark integration for Ordeq"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
requires-python = ">=3.10"
dependencies = [
    "ordeq>=1.2.0",
    "pyspark>=3.3.1",
]

[tool.ordeq-dev]
group = "ios"
logo_url = "https://icon.icepanel.io/Technology/svg/Apache-Spark.svg"

[dependency-groups]
test = [
    "pymssql==2.3.7",
    "testcontainers==4.8.1",
    "pyspark>=3.3.1,<4.0.0",  # no iceberg spark runtime for spark>=4.0.0 yet to use in the tests
    "ordeq-common",
]

[tool.setuptools_scm]
root = "../../"
version_file = "src/ordeq_spark/_version.py"
tag_regex = "^ordeq-spark/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match ordeq-spark/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]
addopts = "--doctest-modules --import-mode=importlib"

[tool.coverage.run]
omit = [
    "src/ordeq_spark/_version.py"
]
